# Generated by Django 5.0.7 on 2024-07-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinstance',
            name='imginst',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filecon.imageinstance')),
            ],
        ),
    ]
