# Generated by Django 5.0.7 on 2024-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecon', '0002_alter_imageinstance_imginst_imagecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecollection',
            name='collection',
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='collection',
            field=models.ManyToManyField(to='filecon.imageinstance'),
        ),
    ]
